// SPDX-FileCopyrightText: 2023 Iván Szkiba
//
// SPDX-License-Identifier: MIT

// Code generated by 'yaegi extract github.com/PaesslerAG/jsonpath'. DO NOT EDIT.

package jetstream

import (
	"github.com/nats-io/nats.go/jetstream"
	"reflect"
)

func init() {
	Symbols["github.com/nats-io/nats.go/jetstream/jetstream"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Publish": 		reflect.ValueOf(jetstream.Publisher.Publish),
		"PublishAsync": 		reflect.ValueOf(jetstream.Publisher.PublishAsync),
		"PublishAsyncComplete": 		reflect.ValueOf(jetstream.Publisher.PublishAsyncComplete),
	}
}
