// SPDX-FileCopyrightText: 2023 Iván Szkiba
//
// SPDX-License-Identifier: MIT

// Code generated by 'yaegi extract github.com/PaesslerAG/jsonpath'. DO NOT EDIT.

package jsonpath

import (
	"github.com/nats-io/nats.go"
	"reflect"
)

func init() {
	Symbols["github.com/nats-io/nats.go/nats"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"UserCredentials": 		reflect.ValueOf(nats.UserCredentials),
	}
}
